### ISSUE TITLE
YouCompleteMe unavailable: requires Vim compiled with Python (3.6.0+) support.

### ISSUE THREAD

**Issue by fschlueter** [image357/.vim#4]
Hi @image357,
i got a little trouble installing vim on a server, I get the error when starting vim as above. The machines themself use py2.7, but I am loading a python3 compiler via cvmfs. Vim is installed via spack (the system installation is to old). I am not quite sure if spack actually installs vim with python2.7 or if when starting vim it only finds the system interpreter. Would you know how to figure out which interpreter is used for installing or if it is a problem during run time (the installation works and install.py is called with py3). 
Cheers,

**Comment by image357** [comment]
please reopen if its still a problem on the current master
